### ISSUE TITLE
Error after first component

### ISSUE THREAD

**Issue by Uceef94** [mhmiton/laravel-modules-livewire#1]
Hi,
Thank you for making this package, I've tried it and I was able to make the first module with a livewire component + view. When I tried to add a second livewire component to the same module I started getting the error as follow:
![image](https://user-images.githubusercontent.com/42481114/103945810-06da8480-5136-11eb-83a0-09e17ebe9895.png)

**Comment by mhmiton** [comment]
Hi, can we connect with TeamViewer? It's helpful for me to find out this
issue. I will try to solve this issue from your code. My skype ID is
"mhmiton". We can connect for the live chat.

>

**Comment by mhmiton** [comment]
This issue is solved. Please remove this package manually and install it again. Hope it will work.
