### ISSUE TITLE
Error when using rappasoft/laravel-livewire-tables

### ISSUE THREAD

**Issue by lparede** [mhmiton/laravel-modules-livewire#10]
@mhmiton , first of all, great work on this package!

I had problem when I start using the package rappasoft/laravel-livewire-tables.

The problem is that the component class is declared like this (DataTableComponent, not Component):
`class UsersTable extends DataTableComponent {`

And in your service provider you are only accepting Component classes:
`->filter(function ($class) { return is_subclass_of($class, Component::class) && ! (new ReflectionClass($class))->isAbstract();            })
`

To solve my problem, I extended this service provide and comment this code: `is_subclass_of($class, Component::class) &&` 

Maybe you can check this, in order to improve this excellent package.

**Comment by mhmiton** [comment]
@lparede  I checked  with [rappasoft/laravel-livewire-tables](https://github.com/rappasoft/laravel-livewire-tables) package. It's working for me. I didn't change anything. Are you getting any errors?

**Comment by lparede** [comment]
@mhmiton , you're absolutly right! There was another error causing this problem and I tought that it was caused by is_subclass_of() function.

My apologies.

You can close this thread.

**Comment by mhmiton** [comment]
Ok, thanks.
