### ISSUE TITLE
Invalid route action: [Modules\Core\Http\Controllers\Modules\Core\Http\Livewire\Pages\HomePage]

### ISSUE THREAD

**Issue by Adroit11** [mhmiton/laravel-modules-livewire#12]
Hi,
After installing the Laravel 8 latest version v8.52.0, I got this Error :

`Modules\Core\Http\Controllers\Modules\Core\Http\Livewire\Pages\HomePage` was not found.
Controller class Modules\Core\Http\Controllers\Modules\Core\Http\Livewire\Pages\HomePage for one of your routes was not found. Are you sure this controller exists and is imported correctly?

Thanks

**Comment by mhmiton** [comment]
Maybe this is the route namespace issue. You should remove the route namespace from the modules route service provider. You can check this - https://github.com/mhmiton/laravel-modules-livewire/issues/2#issuecomment-761831051
