### ISSUE TITLE
How its works? 

### ISSUE THREAD

**Issue by osmaircoelho** [mhmiton/laravel-modules-livewire#13]
First of all, do I have to create a new module like this?
`php artisan module:make <module-name>`

Because I Running those commands
 `php artisan module:make-livewire Pages/AboutPage Core`
`php artisan module:make-livewire Pages\\AboutPage Core`
`php artisan module:make-livewire pages.about-page Core`

 and I have this error
 `Nwidart\Modules\Exceptions\ModuleNotFoundException`
 `Module [Pages/AboutPage] does not exist!`
 
when I running this command its works
`php artisan module:make-livewire Core Pages/AboutPage`

my file modules_statuses.json

`{
    "Core": true,
    "Stock": true,
    "HR": true
}`

**Comment by mhmiton** [comment]
Can you check this package version that you used, please? It will work for the version of 1.2.0.

**Comment by osmaircoelho** [comment]
Hi, guys how are you? apologies for the delay!

I was using version 1.2.0, but I think it is not wasn't what caused the error, I updated to version 1.3.0

 I ran this command first
 
`php artisan module:make <module-name>` to create the module

so then I ran 
`php artisan module:make-livewire Pages/AboutPage <module>`

I had to create the module first of all and then I ran the commando to create livewire pages.

**Comment by mhmiton** [comment]
@osmaircoelho Are you getting this error with version 1.3.0?

**Comment by osmaircoelho** [comment]
yes the same error

**Comment by mhmiton** [comment]
Ok. Can you share your demo project with me or can we add with discord? This is my discord id - `mhmiton#8254`. Please add me. If you feel free, I will try to solve this issue on your PC.

**Comment by osmaircoelho** [comment]
hey, @mhmiton do not worry about that! I just was testing, this is not a big project, and  I do not have good experience in Laravel.
