### ISSUE TITLE
Request feature for manually loaded modules' custom namespace different from Modules and an optional source directory

### ISSUE THREAD

**Issue by sornss** [mhmiton/laravel-modules-livewire#14]
Hello

I would like to thank you for the package.

Can we please make it possible for the ability to specify the modules's namespace different from the default Modules and a nullable source directory?

Below is the custom concerned structure:

packages/vendorA/module1/src

Thank you in advance.

**Comment by mhmiton** [comment]
Thanks for using this package. Need some discussion about this feature for more clearance. Can we add on [discord.com](https://discord.com), please? This is my discord id - `mhmiton#8254`.

**Comment by mhmiton** [comment]
Ok. I checking and trying to add this feature.
