### ISSUE TITLE
Getting Erorr on installation

### ISSUE THREAD

**Issue by rajkumarchanda** [mhmiton/laravel-modules-livewire#18]
ErrorException

  Trying to access array offset on value of type null

  at D:\Project\stest\vendor\nwidart\laravel-modules\src\LaravelModulesServiceProvider.php:59
     55▕             return new Laravel\LaravelFileRepository($app, $path);
     56▕         });
     57▕         $this->app->singleton(Contracts\ActivatorInterface::class, function ($app) {
     58▕             $activator = $app['config']->get('modules.activator');
  ➜  59▕             $class = $app['config']->get('modules.activators.' . $activator)['class'];
     60▕
     61▕             if ($class === null) {
     62▕                 throw InvalidActivatorClass::missingConfig();
     63▕             }

  1   D:\Project\stest\vendor\nwidart\laravel-modules\src\LaravelModulesServiceProvider.php:59
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Trying to access array offset on value of type null", "D:\Project\stest\vendor\nwidart\laravel-modules\src\LaravelModulesServiceProvider.php", [Object(Illuminate\Foundation\Application)])

  2   D:\Project\stest\vendor\laravel\framework\src\Illuminate\Container\Container.php:873
      Nwidart\Modules\LaravelModulesServiceProvider::Nwidart\Modules\{closure}(Object(Illuminate\Foundation\Application), [])

**Comment by mhmiton** [comment]
This error is showing from the [nWidart/laravel-modules](https://github.com/nWidart/laravel-modules) package. Maybe need to publish the [nWidart/laravel-modules](https://github.com/nWidart/laravel-modules) config. Please publish the config and try again - 

`php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"`
