### ISSUE TITLE
Developer Please Read

### ISSUE THREAD

**Issue by silicahd** [mhmiton/laravel-modules-livewire#19]
I am kind of worried as Hassan has disappeared as of December. All his social media posting has stopped since than.  If anybody knows that he is ok please post here.

**Comment by mhmiton** [comment]
Are you talking about @Hassan? Please send me more details about @Hasan to my Gmail - mhmiton.dev@gmail.com

**Comment by silicahd** [comment]
> Are you talking about @hassan? Please send me more details about @hasan to my Gmail - [mhmiton.dev@gmail.com](mailto:mhmiton.dev@gmail.com)

Nope I was actually looking for you and thought something has happened to you. I sent you an email a few days ago.
