### ISSUE TITLE
Routing Issue

### ISSUE THREAD

**Issue by Uceef94** [mhmiton/laravel-modules-livewire#2]
Hello,
There is another issue when using the module's web route, included is a screenshot where I marked the path in yellow that should be removed in case livewire is used instead of a controller
![Route](https://user-images.githubusercontent.com/42481114/104821550-f82e5480-583c-11eb-9ec2-870ac9b20c4b.PNG)

**Comment by mhmiton** [comment]
Maybe this is a route namespace issue. Laravel 8 natively removed the route namespace. But in the modules package using route namespace.  You should remove the route namespace from every module RouteServiceProvider.  Try using this. Hope it will work.

RouteServiceProvider Path: Modules/Bank/Providers/RouteServiceProvider.php

```
protected function mapWebRoutes()
{
    Route::middleware('web')
        // ->namespace($this->moduleNamespace) // Removed For Livewire Route
        ->group(module_path('Bank', '/Routes/web.php'));
}
```

Also, I created a example repository with the Livewire route. You can check it.

**Example Source Code:** [https://github.com/mhmiton/laravel-modules-livewire-example](https://github.com/mhmiton/laravel-modules-livewire-example)

**Example Live Demo:** [https://dev.mhmiton.com/laravel-modules-livewire-example](https://dev.mhmiton.com/laravel-modules-livewire-example)

**Comment by Uceef94** [comment]
Thank you it did work!
