### ISSUE TITLE
Target class [Livewire\Livewire\Commands\MakeCommand] does not exist.

### ISSUE THREAD

**Issue by tarikhagustia** [mhmiton/laravel-modules-livewire#23]
i have this error while generating command

**Comment by mhmiton** [comment]
Which Laravel, Laravel-Livewire, and Laravel-Modules-Livewire version you are using?

**Comment by tarikhagustia** [comment]
Laravel Framework 8.42.1
livewire/livewire                    v2.3.8
mhmiton/laravel-modules-livewire     v1.5.0 
nwidart/laravel-modules              v8.3.0

**Comment by mhmiton** [comment]
I checked with these versions. I didn't find any issues. Is possible to share your demo project or maybe it will be better if I connect with your pc and try to find issues. Can we add on [discord.com](https://discord.com/), please? This is my discord id - `mhmiton#8254`.
