### ISSUE TITLE
Error when using slots in Laravel modules Livewire components

### ISSUE THREAD

**Issue by DanielRondonGarcia** [mhmiton/laravel-modules-livewire#25]
I'm trying to use slots in a Livewire component inside a Laravel module, but it's giving me the following error:

```
ErrorException
Undefined variable $slot (View: C:\wamp64\www\laravel\Modules\User\Resources\views\livewire\test.blade.php)
```

The component code is as follows:

```html
<div>
    <h3>The <code>{{ $slot }}</code> livewire component is loaded from the <code>{{ $options }}</code> module.</h3>
</div>
```

And in the view I am using the component as follows:

```php
<livewire:user::test>
    @slot('slot')
        Test
    @endslot
    @slot('options')
        User
    @endslot
</livewire:user::test>
```

Has anyone had a similar problem or knows how to fix it?

**Comment by mhmiton** [comment]
@DanielRondonGarcia Maybe the livewire component doesn't support the slot things. So, you can use props instead of slots. Please, check these resources.

### Add component slots - https://github.com/livewire/livewire/issues/68
### Slots in Livewire - https://github.com/livewire/livewire/issues/941
