### ISSUE TITLE
wire:click doesnt work for me

### ISSUE THREAD

**Issue by falahatiali** [mhmiton/laravel-modules-livewire#28]
I have this button but doesnt work for me.

I have a Module its name is Chat and its inside this module

`
<button class="btn btn-primary btn-block mb-4" wire:click="createNewChat"> + Create a new Chat </button>
`

**Comment by mhmiton** [comment]
@falahatiali Can you provide the component **class** and **view** file source code, please?

**Comment by falahatiali** [comment]
@mhmiton yes of course: 
my project is inside Chat module. 



```
    <div class="col-lg-3">
        <div class="sidebar">
            <button class="btn btn-primary btn-block mb-4" wire:click.prevent="createNewChat"> + Create a new Chat </button>
            <hr>
            @foreach($chats as $chat)
                <a href="">{{ $chat->title ?? 'New Chat' }}</a><br>
            @endforeach
        </div>
    </div>
    
    ```
    
    
    
    ```
    class Home extends Component
{
    public $chats = [];

    public $selectedChat;

    public function mount()
    {
        $this->chats = Chat::query()->get();
    }

    public function selectChat(int $chatId)
    {
        $this->selectedChat = Chat::query()->find($chatId);
    }

    public function createNewChat()
    {
        dd($this);
    }
    public function render()
    {
        return view('chatgpt::livewire.home');
    }
}

    ```

**Comment by mhmiton** [comment]
@falahatiali This seems to work. But, it is pretty difficult to find out this issue in this way. So, you can feel free to join with me in [discord](https://discord.com), so I will try to find out this issue on your pc or source code.

This is my discord id - `mhmiton#8254`
