### ISSUE TITLE
Invalid Route

### ISSUE THREAD

**Issue by diorz38** [mhmiton/laravel-modules-livewire#3]
when i try to create Livewire Module, this us what happen:

```
UnexpectedValueException
Invalid route action: [Modules\Backend\Http\Controllers\Modules\Backend\Http\Livewire\Pengguna\IndexPage].`
```

step to reproduce:
install laravel 8,
package i use:

```
        "laravel/framework": "^8.12",
        "livewire/livewire": "^2.3",
        "mhmiton/laravel-modules-livewire": "dev-master",
        "nwidart/laravel-modules": "^8.0",
```
in terminal:
```
php artisan vendor:publish --provider="Mhmiton\LaravelModulesLivewire\LaravelModulesLivewireServiceProvider"
php artisan module:make Backend
php artisan module:make-livewire Backend Pengguna/IndexPage
```

in routes/web.php (inside modules Backend):
```
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
 */

Route::get('/pengguna', \Modules\Backend\Http\Livewire\Pengguna\IndexPage::class)->name('pengguna.index');
```

in my component:
```
<?php

namespace Modules\Backend\Http\Livewire\Pengguna;

use Livewire\Component;

class IndexPage extends Component
{
    public function render()
    {
        return view('backend::livewire.pengguna.index-page')
            ->extends(config('backend.extends.default'));
    }
}
```

my module Config:
```
<?php

return [
    'name' => 'Backend',
    'extends' => [
        'default' => 'backend::layouts.dafault'
    ]
];
```

when i change mabWebroute just like you suggest, to this:

```
    protected function mapWebRoutes()
    {
        Route::middleware('web')
            // ->namespace($this->moduleNamespace)
            ->group(module_path('Backend', '/Routes/web.php'));
    }
```
another error appear:

```
InvalidArgumentException
View [layouts.dafault] not found. (View:
```

but i make sure that layouts default.blade.php exist

**Comment by mhmiton** [comment]
Please try this solution - https://github.com/mhmiton/laravel-modules-livewire/issues/2#issuecomment-761831051

**Comment by diorz38** [comment]
yes i have try that, but another error appear:

```
InvalidArgumentException
View [layouts.dafault] not found.
```

**Comment by mhmiton** [comment]
Maybe you need to config:cache and make sure the layout blade file is 'layouts.dafault'. Can you provide your Backend module views folder screenshot and layout's source code, please?

**Comment by diorz38** [comment]
After performed `php artisan optimize:clear` its all good now, except the module's route for a page without livewire still broke.
hope u'll solve that soon.

thx

**Comment by mhmiton** [comment]
You removed the module route namespace, so you should use the laravel default route like this - 

```
use Modules\Auth\Http\Controllers\Backend\LoginController as BackendLoginController;
use Illuminate\Support\Facades\Route;

Route::get('backend/login', [BackendLoginController::class, 'index'])->name('backend.login');
```

You can check this - https://laravel.com/docs/8.x/routing#the-default-route-files

Also, I will try to add a separate route macro to support the module route namespace in this package.
