### ISSUE TITLE
Class "Livewire\Features\SupportConsoleCommands\Commands\MakeCommand" not found

### ISSUE THREAD

**Issue by aeq-dev** [mhmiton/laravel-modules-livewire#31]
After upgrading to the latest version 1.6, Laravel 10, Livewire 2.x 
I'm getting this error on running module:make-livewire 

` pa module:make-livewire Payments/ImportPaymentData Accounting`

   ```
Error 

  Class "Livewire\Features\SupportConsoleCommands\Commands\MakeCommand" not found

  at vendor/mhmiton/laravel-modules-livewire/src/Traits/CommandHelper.php:156
    152▕     }
    153▕ 
    154▕     protected function isClassNameValid($name)
    155▕     {
  ➜ 156▕         return (new \Livewire\Features\SupportConsoleCommands\Commands\MakeCommand())->isClassNameValid($name);
    157▕     }
    158▕ 
    159▕     protected function isReservedClassName($name)
```

**Comment by mhmiton** [comment]
@aeq-dev Can you run `composer update` first and try again, please?

**Comment by aeq-dev** [comment]
I did and still same error

**Comment by aeq-dev** [comment]
I removed the whole vendor folder and install it again, 
in composer : ` "mhmiton/laravel-modules-livewire": "^1.6",`

Still same error :/

**Comment by mhmiton** [comment]
Please try again now, hope it will be work.

**Comment by aeq-dev** [comment]
Did you push anything ? No thing has been changed :)

**Comment by mhmiton** [comment]
I deleted just tag v1.7.0. Still, It's not working?

**Comment by aeq-dev** [comment]
Yes still error, and remove v1.7 doesn't change my composer coz it's using 1.6

**Comment by mhmiton** [comment]
I just re-install the v1.6.0, and it's working on my end. Can you try again to re-install, please?

**Comment by aeq-dev** [comment]
Now it works, thanks
