### ISSUE TITLE
version 2.0.0 supported only livewire v3 

### ISSUE THREAD

**Issue by XarchencoMO** [mhmiton/laravel-modules-livewire#32]
if you install laravel 10 + livewire v2 + laravel-modules + Laravel-modules-livewire, and write in console: 
php artisan module:make-livewire <component_name> <module_name>  
you will get an error "livewire makeCommand not found"

**Comment by mhmiton** [comment]
@XarchencoMO If you working with livewire v2, you need to install v1.6.0.
