### ISSUE TITLE
How to use @livewire syntax

### ISSUE THREAD

**Issue by PKDmeDEV** [mhmiton/laravel-modules-livewire#34]
Hi,
I have a module `Components`.
- This one is working
`
<livewire:components::blog.blog-preview-component1 />
`
- This one is not working
`
@livewire('components::livewire.blog.blog-preview-component1')
`
What is the correct syntax ?

Thanks

**Comment by mhmiton** [comment]
@PKDmeDEV Hi, you can try this -

`@livewire('components::blog.blog-preview-component1')`

**Comment by PKDmeDEV** [comment]
Thanks, it worked. Sorry couldn't test it earlier.
