### ISSUE TITLE
Unable to find component: [demos::demos-page]

### ISSUE THREAD

**Issue by rabol** [mhmiton/laravel-modules-livewire#38]
Hi

iIhave installed
```
https://github.com/dcblogdev/laravel-module-generator
```
and created a new module, and it works fine.

Now I created a Livewire component:
```
php artisan module:make-livewire Demos/IndexPage Demos
```

output:
```
CLASS: Modules/Demos/Livewire/Demos/IndexPage.php
VIEW:  Modules/Demos/Resources/views/livewire/demos/index-page.blade.php
TAG: <livewire:demos::demos-page />
```

then in a view of the module I have this:
```
<livewire:demos::demos-page />
```

but when I try to access the page I get:
```
Unable to find component: [demos::demos-page]
```

I'm sure I missed something, but not sure what

**Comment by mhmiton** [comment]
@rabol Please try this and let me know if it works or not.

`<livewire:demos::demos.index-page />`

**Comment by rabol** [comment]
yes that works
