### ISSUE TITLE
Component not found in Livewire's post update method

### ISSUE THREAD

**Issue by jorgeluiz1586** [mhmiton/laravel-modules-livewire#39]
I set up my Laravel application to work by modules, I created the first module which is the Dashboard module and in it there are components in **/modules/Dashboard/app/Livewire/Pages**

The system works until I use wire:click to update a property in the component, it simply results in an error with status 500 in the post type route in **localhost:8000/livewire/update** it says the following: 

![Captura de tela de 2024-02-20 22-11-18](https://github.com/mhmiton/laravel-modules-livewire/assets/50534419/8ae6f20f-a6fb-40f8-b2aa-04f7f82f3e21)
 
I tested with components outside the Dashboard module and the update works, but in the module it gives an error.

**Comment by mhmiton** [comment]
@jorgeluiz1586 Did you configure the livewire namespace path on the config file for - /modules/Dashboard/app/Livewire?

By default the namespace will be used - /modules/Dashboard/Livewire.

**Comment by jorgeluiz1586** [comment]
Yes, I configured the namespace in composer.json, so much so that it only gives an error when the Livewire update route is executed.

I'll set up this default namespace to see if it works

**Comment by jorgeluiz1586** [comment]
I managed to solve the problem, in the Livewire\Mechanisms\ComponentRegistry file on line 115 a wrong Namespace is checked, it joins the base name space with that of the module, so App\Livewire\Modules\Dashboard\App\Livewire\Pages\Instances\Index I fixed it by making a command in Artisan that replaces this file with a similar file with a treatment to check if it's a Livewire component class from a module or from the root when it's from a module I delete App\Livewire and the Index end of the wrong namespace App\Livewire\Modules\Dashboard\App\Livewire\Pages\Instances\Index and it's working, I'll finish this conversation, thank you very much for your attention
