### ISSUE TITLE
Composer Error

### ISSUE THREAD

**Issue by windsondias** [mhmiton/laravel-modules-livewire#4]
Hello @mhmiton!

Would you help me? When I try to install the package I get the following error:

"Could not find a version of package mhmiton/laravel-modules-livewire matching your minimum-stability (dev). Require it with an explicit version constraint allowing its desired stability."

I don't have much knowledge in composing. All the solutions I found on the web did not solve.

I tried to run:

composer require mhmiton/laravel-modules-livewire
composer require mhmiton/laravel-modules-livewire:dev-master

"mhmiton/laravel-modules-livewire": "dev-master"
composer update

If you can help me thank you in advance!!

**Comment by mhmiton** [comment]
Which version of Laravel do you use?

**Comment by windsondias** [comment]
Laravel Framework 8.15.0
Laravel Modules ^8.2

**Comment by mhmiton** [comment]
I re-checked. Also, it's working on my end. You can remove the "composer.lock" file before package installing and try to install by this command

`composer require mhmiton/laravel-modules-livewire dev-master`

**Comment by windsondias** [comment]
![image](https://user-images.githubusercontent.com/57019436/106642129-bd2f5f00-6566-11eb-89d1-0305aa0c4643.png)

I removed composer.lock and ran the command, returned the print error. If it's working for you it's probably something in my environment.

**Comment by mhmiton** [comment]
When are you installing other packages, this return the same error?

**Comment by windsondias** [comment]
No, they work normally.
In that same project I just installed fortify and had no problems, I have other projects with other packages and installed without problems too.

**Comment by mhmiton** [comment]
Oh, it's also hard to solve this issue in this way. Can we add with [discord](https://discord.com)? This is my discord id - `mhmiton#8254`. Please add me. If you feel free, I will try to solve this issue on your PC.
