### ISSUE TITLE
Invalid Route Action

### ISSUE THREAD

**Issue by T3mmyKay** [mhmiton/laravel-modules-livewire#43]
I am trying to use this package, I didn't change the config in order to avoid errors but when I am trying to use full page components, I keep getting invalid route action.
![image](https://github.com/mhmiton/laravel-modules-livewire/assets/103121606/6bf4a5d2-83f7-4f4e-88d2-6c32b89efd0a)
This is my class component.

![image](https://github.com/mhmiton/laravel-modules-livewire/assets/103121606/e4c54255-e988-4550-9637-6a8a27d4b17b)
The web.php of my module. I am using laravel 11 along with the latest version of laravel modules

**Comment by mhmiton** [comment]
@T3mmyKay Please update this package to v3 and try again.

**Comment by T3mmyKay** [comment]
I am trying to use livewire volt with modular namespace 

` Volt::route('units', `'products::units')->name('units.index');`

I am getting component not found

**Comment by mhmiton** [comment]
@T3mmyKay You can try with the component's full class name. Like this -

`Volt::route('about', Modules\Blog\Livewire\Pages\AboutPage::class);`
