### ISSUE TITLE
wire-elements Support

### ISSUE THREAD

**Issue by jcabanillas** [mhmiton/laravel-modules-livewire#48]
Hello;
I'm using this package [wire-elements](https://github.com/wire-elements/modal)

When I do this:

`
<button type="button"
      wire:click="$dispatch('openModal', { component: 'ventas::components.venta-detalle-modal' })" class="btn btn-success">
<i class="bi bi-plus"></i> Producto
</button>
`

This error appears :

Livewire\Exceptions\ComponentNotFoundException
Unable to find component: ventas::components.venta-detalle-modal

My module is under path Modules/Ventas/app/Livewire/Components/VentaDetalleModal.php

Any help please
Thanks.

**Comment by mhmiton** [comment]
It seems to be ok. Also, can you check the namespace or path configuration?

Or, can you share your demo project with me or can we add it to Discord? This is my discord ID - mhmiton#8254. Please add me. Will try to solve this issue on your PC if you feel free.
