### ISSUE TITLE
Using the @livewire tag in blade

### ISSUE THREAD

**Issue by AutiCodes** [mhmiton/laravel-modules-livewire#49]
Hi, i was looking through you're example but i could not find how to use the Livewire inside an blade.

I have made an Livewire with php artisan module:make-livewire <name> <module> and that works. Tho i think i need more info in the @livewire tag because it says 'include(C:\Users\autic\Development\Kyomi-V2\vendor\composer/../../app/Livewire/ShowFlights.php): Failed to open stream: No such file or directory"

**Comment by mhmiton** [comment]
@AutiCodes  Did you try this?

`@livewire('{module-lower-name}::show-flights')`

**Comment by AutiCodes** [comment]
![image](https://github.com/user-attachments/assets/11988723-e706-4ad9-96cf-0007ac326e38)

I got a little bit further

**Comment by mhmiton** [comment]
I checked with @livewire on my end, it is also working. Could you send me the config file and component code or share with me a demo project? I will try to find out the issue on my end.
