### ISSUE TITLE
Livewire not found error

### ISSUE THREAD

**Issue by saraswat19** [mhmiton/laravel-modules-livewire#50]
I am trying to create a component on my Jetstream Livewire project but getting the following error.

Laravel Framework 11.30.0

livewire/livewire  -  v3.5.12

![image](https://github.com/user-attachments/assets/65dab02b-29d7-4153-a11e-116478c62735)

**Comment by mhmiton** [comment]
@saraswat19 Sorry for the late response. Have you installed the livewire and make sure the `livewire/livewire` path is exists in the vendor folder, please?

**Comment by saraswat19** [comment]
> @saraswat19 Sorry for the late response. Have you installed the livewire and make sure the `livewire/livewire` path is exists in the vendor folder, please?

Yes. It exists. Livewire component is working normally but not when I am trying to create via your package on jetstream liveiwre.

**Comment by saraswat19** [comment]
That fixed it. Thanks

> @saraswat19 I solved this issue. Please update the package to version 4.2.0. Thanks.

**Comment by saraswatabhinav** [comment]
This issue is happening again. Please check and fix urgently.

**Comment by mhmiton** [comment]
@saraswatabhinav Which version are you using?

Laravel:
Livewire:
Laravel Modules:
Laravel Modules Livewire:

**Comment by saraswatabhinav** [comment]
Sorry, my mistake. 

It works now. I upgraded to v5.0.0
