### ISSUE TITLE
Volt support

### ISSUE THREAD

**Issue by dcblogdev** [mhmiton/laravel-modules-livewire#51]
Just wondering if it would be possible to configure the package to support Volt, do you think that would be possible?

**Comment by mhmiton** [comment]
@dcblogdev I tried that before. But, I couldn't find an option to register the Volt component with a module alias.

Also, this is works -

For Blog module -

```
BlogServiceProvider:

\Livewire\Volt\Volt::mount([
    \Module::getModulePath('Blog').'resources/views/livewire',
    \Module::getModulePath('Blog').'resources/views/pages',
]);

Volt Component: Blog/resources/views/pages/list.blade.php

Volt::route('blogs', 'list');
```

But, with the alias is not working -

`Volt::route('blogs', 'blog::list');`

Also, I am trying to find another way. Do you have any suggestions, please?

**Comment by dcblogdev** [comment]
yes same for me. I can load a view but not with a module:: prefix.

So a work around to avoid conflicts would be to create a folder with the same name as the module.

So in the service provider:

```php
Volt::mount(Module::getModulePath($this->moduleName).'resources/views/livewire');
```

then have a path like `Modules/Base/resources/livewire/base/contact.php`

Then a route like:

`Volt::route('/contact', 'base.contact');`

**Comment by dcblogdev** [comment]
so doesn't look like anything you can do at the package level, I'll close this.
