### ISSUE TITLE
Issue with Laravel 11.31 once install causing "php artisan view:cache" missing whole chunk of framework and exception blade.

### ISSUE THREAD

**Issue by irvine48** [mhmiton/laravel-modules-livewire#52]
Before Install 
![image](https://github.com/user-attachments/assets/41cad532-8ff5-4f7a-8ff9-5f15ae1980bc)

After Install
![image](https://github.com/user-attachments/assets/94215b9e-0c00-4f3e-abd3-4f00bab0ad45)
Only this part generated.

![image](https://github.com/user-attachments/assets/96ab8bb8-07be-444e-8280-73c435e626fd)

downgrade to 3.0.0 work as usual.

**Comment by hardlevel** [comment]
i'm with the same error after the instllation

**Comment by nathanjansen** [comment]
Same here

**Comment by mhmiton** [comment]
@irvine48 @hardlevel @nathanjansen @jurrid Hi, I checked with the fresh Laravel 11 project. I did not face any issues. The `php artisan view:cache` command works on my end. Could you share a dummy project with me, please? So, I will check it.

**Comment by irvine48** [comment]
@mhmiton maybe some of us install https://github.com/jantinnerezo/livewire-alert
I attached a sample error project.
[example-app.zip](https://github.com/user-attachments/files/17934436/example-app.zip)

**Comment by jurrid** [comment]
I can pinpoint the issue to the changes in `3.0` to `4.0`

**Comment by jurrid** [comment]
The drill down leads me to this function, when "turning off" the extend the code is working again. 

```php
public function registerModuleVoltViewFactory()
{
    $this->app->extend('view', function ($service, $app) {
        $engineResolver = $app['view.engine.resolver'];
        $finder = $app['view.finder'];
        $dispatcher = $app['events'];

        return new ModuleVoltViewFactory($engineResolver, $finder, $dispatcher);
    });

    \View::clearResolvedInstance('view');
}
```

**Comment by mhmiton** [comment]
@irvine48 @hardlevel @nathanjansen @jurrid Hopefully, the issue is solved. Please update the version 4.3. Thanks.

**Comment by irvine48** [comment]
![image](https://github.com/user-attachments/assets/27f22339-b4ce-464a-b700-06a89b27f2e5)

Yup, it is working now. thank you for the quick fix.
