### ISSUE TITLE
Error composer

### ISSUE THREAD

**Issue by uarefans** [mhmiton/laravel-modules-livewire#7]
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   ErrorException 

  Trying to access array offset on value of type null

  at vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php:59
     55▕             return new Laravel\LaravelFileRepository($app, $path);
     56▕         });
     57▕         $this->app->singleton(Contracts\ActivatorInterface::class, function ($app) {
     58▕             $activator = $app['config']->get('modules.activator');
  ➜  59▕             $class = $app['config']->get('modules.activators.' . $activator)['class'];
     60▕ 
     61▕             if ($class === null) {
     62▕                 throw InvalidActivatorClass::missingConfig();
     63▕             }

      +24 vendor frames 
  25  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()

      +5 vendor frames 
  31  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

error when install

**Comment by mhmiton** [comment]
Which PHP version are you using?

**Comment by uarefans** [comment]
PHP 8.0.5
"nwidart/laravel-modules": "^8.2",
"livewire/livewire": "^2.3",
"laravel/framework": "^8.12",

**Comment by babakhakimi** [comment]
i have this issue too
please fix this

**Comment by babakhakimi** [comment]
i have this issue too
please fix this

**Comment by mhmiton** [comment]
@uarefans @babakhakimi Hi, I checked and it's working for me. I didn't found any error. Also, If we connect with your PC, maybe it will easy to fix this error. Can we add with [discord](https://discord.com)? This is my discord id - `mhmiton#8254`. Please add me. If you feel free, I will try to solve this issue on your PC.

**Comment by babakhakimi** [comment]
hi
I understood where the problem came from
at the first I had a problem installing the package.
But now I was able to solve the problem
This is what I did :
first must run this code to publish Nwidart configuration file
`php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"`
then install this package
After that, everything worked fine

thank you

**Comment by mhmiton** [comment]
@babakhakimi Ok, thanks.

**Comment by luiggie97** [comment]
I have the same error, but run this command 
"php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"
doesn't work for me

**Comment by Dawwwid** [comment]
You can try completing the file `/config/modules.php` by adding at the end :
```php
    /*
    |--------------------------------------------------------------------------
    | Activators
    |--------------------------------------------------------------------------
    |
    | You can define new types of activators here, file, database etc. The only
    | required parameter is 'class'.
    | The file activator will store the activation status in storage/installed_modules
    */
    'activators' => [
        'file' => [
            'class' => FileActivator::class,
            'statuses-file' => base_path('modules_statuses.json'),
            'cache-key' => 'activator.installed',
            'cache-lifetime' => 604800,
        ],
    ],

    'activator' => 'file',
```

Incidentally it may need to generate the file `/modules_statuses.json` with `php artisan module:v6:migrate`

Obviously, don't forget to delete the package `mhmiton/laravel-modules-livewire` if the initial error doesn't allow to interact in the console anymore `composer remove mhmiton/laravel-modules-livewire`

It worked for me 👍
