### ISSUE TITLE
No hint path defined for [module name]

### ISSUE THREAD

**Issue by AEK-BKF** [mhmiton/laravel-modules-livewire#8]
Hi,
After updating Laravel 8 to the latest version v8.42.0, I get this Error :

No hint path defined for [x] where 'x' is the module name

Thanks

**Comment by mhmiton** [comment]
Hi, I checked. Maybe this issue is for the [laravel-modules](https://github.com/nWidart/laravel-modules) package. Please, submit this issue in the [laravel-modules](https://github.com/nWidart/laravel-modules) repo. Thanks.
